# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 50
  - name: Recent Blog Posts
    url: '#posts'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Paper/Book Reviews
    url: '#paperreviews'
    weight: 40
  - name: About this site
    url: '#featured'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 60
